### ISSUE TITLE
[Issue] RIS.selectCmDeviceExt throws error in line 166 message when the "device_class" is specificed when method is used

### ISSUE THREAD

**Issue by 2-dor** [awetomate/cucmapi#1]
>>> reg = RIS.selectCmDeviceExt(devices=[""],subs=[""],device_class=["SIPTrunk"])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Users\tnegru\AppData\Local\Programs\Python\Python38\lib\site-packages\cucmapi\ris.py", line 166, in selectCmDeviceExt
    raise ValueError(f"device_class needs to contain one of the following:\n{device_classes}")
ValueError: device_class needs to contain one of the following:
('Any', 'Phone', 'Gateway', 'H323', 'Cti', 'VoiceMail', 'MediaResources', 'HuntList', 'SIPTrunk', 'Unknown')
>>>

**Comment by 2-dor** [comment]
Argument has to be supplied as string.
